#!/usr/bin/python3

import sys
import yaml
from job_creation import *

import pprint
from pprint import pprint as P

if len(sys.argv) > 1:
    file_name = sys.argv[1]
else:
    file_name = "test.yaml"

with open(file_name, "r") as f:
    dataMap = yaml.safe_load(f)

jobs = create_jobs(dataMap)
run_jobs(jobs)
