#!/usr/bin/python3
import sys
import yaml
import logging
import colored_log
import pprint
from pprint import pprint as P
from job_creation import *

handler = logging.StreamHandler()
handler.setFormatter(
    colored_log.ColorFormatter(colored_log.DEFAULT_FMT)
    )

logger = logging.getLogger('remote-jobs')
print(len(logger.handlers))
logger.addHandler(handler)
logger.setLevel(logging.INFO)
logger.propagate=False


if len(sys.argv) > 1:
    file_name = sys.argv[1]
else:
    file_name = "test.yaml"

with open(file_name, "r") as f:
    dataMap = yaml.safe_load(f)
    logging.debug(pprint.pformat(dataMap))

jobs = create_jobs(dataMap)
run_jobs(jobs)
